/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthCheckResponse"];
                    };
                };
                405: components["responses"]["MethodNotAllowed"];
                /** @description Service is shutting down or unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready to serve traffic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
                405: components["responses"]["MethodNotAllowed"];
                /** @description Service is not ready (poller not warmed or failing) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get games by date */
        get: {
            parameters: {
                query: {
                    /** @description YYYY-MM-DD date. */
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Games for the requested date */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodayResponse"];
                    };
                };
                /** @description Missing or invalid date format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                405: components["responses"]["MethodNotAllowed"];
                502: components["responses"]["UpstreamError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The requested game */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Game"];
                    };
                };
                /** @description Invalid or missing game id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Game not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                405: components["responses"]["MethodNotAllowed"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthCheckResponse: {
            /** @enum {string} */
            status: "ok";
        };
        TodayResponse: {
            /** Format: date */
            date: string;
            games: components["schemas"]["Game"][];
        };
        Game: {
            id: string;
            provider: string;
            homeTeam: components["schemas"]["Team"];
            awayTeam: components["schemas"]["Team"];
            /** Format: date-time */
            startTime: string;
            status: string;
            /** @enum {string} */
            statusKind: "SCHEDULED" | "IN_PROGRESS" | "FINAL" | "POSTPONED" | "CANCELED";
            score: components["schemas"]["Score"];
            meta: components["schemas"]["GameMeta"];
        };
        Team: {
            id: string;
            name: string;
            fullName?: string;
            abbreviation?: string;
            city?: string;
            conference?: string;
            division?: string;
        };
        Player: {
            id: string;
            firstName: string;
            lastName: string;
            position?: string;
            heightFeet?: number;
            heightInches?: number;
            weightPounds?: number;
            height?: string;
            weight?: string;
            team: components["schemas"]["Team"];
            meta: components["schemas"]["PlayerMeta"];
        };
        PlayerMeta: {
            upstreamPlayerId: number;
            college?: string;
            country?: string;
            jerseyNumber?: string;
            height?: string;
            weight?: string;
            draftYear?: number;
            draftRound?: number;
            draftNumber?: number;
        };
        Score: {
            home: number;
            away: number;
        };
        GameMeta: {
            season: string;
            upstreamGameId: number;
            period?: number;
            postseason?: boolean;
            time?: string;
        };
        ErrorResponse: {
            error: string;
            requestId?: string;
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ready";
        };
    };
    responses: {
        /** @description Upstream provider unavailable */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
                examples: unknown;
            };
        };
        /** @description Method not allowed */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
